apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: dev
build:
  artifacts:
    - image: andreibarbuoz/lnkshrtn
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: lnkshrtn
        createNamespace: true
        chartPath: deploy/lnkshrtn
        artifactOverrides:
          image: andreibarbuoz/lnkshrtn
        imageStrategy:
          helm: {}
        namespace: lnkshrtn
---
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: e2e
build:
  artifacts:
    - image: andreibarbuoz/lnkshrtn-e2e
      docker:
        dockerfile: e2e.Dockerfile
deploy:
  helm:
    releases:
      - name: lnkshrtn
        createNamespace: true
        chartPath: deploy/lnkshrtn
        artifactOverrides:
          image: andreibarbuoz/lnkshrtn-e2e
        imageStrategy:
          helm: {}
        namespace: lnkshrtn
        valuesFiles:
          - "deploy/lnkshrtn/e2e-values.yaml"
