apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: andreibarbuoz/lnkshrtn
deploy:
  helm:
    releases:
      - name: lnkshrtn
        chartPath: deploy/lnkshrtn
        artifactOverrides:
          image: andreibarbuoz/lnkshrtn
        imageStrategy:
          helm: {}
        namespace: lnkshrtn
